# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYNews

    pod 'SwiftyJSON', '~> 4.1.0'
    pod 'Kingfisher', '~> 4.9.0'
    pod 'ObjectMapper', '~> 3.4.2'
    pod 'Alamofire', '~> 4.7.3'
    pod 'AlamofireObjectMapper', '~> 5.1.0'
    pod 'SugarRecord/CoreData', '~> 3.1.2'
    pod 'SwiftGen', '~> 6.4.0'

  target 'NYNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
